import { test, expect } from '@playwright/test'
let pageErrors: string[] = []
test.beforeEach(async ({ page }) => { pageErrors = []; page.on('pageerror', error => pageErrors.push(error.message)) })
test.afterEach(() => { expect(pageErrors).toEqual([]) })
test('真实组件：新增成功后显示，删除成功后消失', async ({ page }) => {
  await page.goto('/')
  await expect(page.getByRole('cell', { name: '示例用户', exact: true })).toBeVisible()
  await page.getByRole('button', { name: '新增用户' }).click()
  const dialog = page.getByRole('dialog')
  await dialog.getByLabel('用户名').fill('测试新增')
  await dialog.getByLabel('邮箱').fill('test@example.com')
  await dialog.getByRole('button', { name: 'OK' }).click()
  await expect(dialog).not.toBeVisible()
  const row = page.getByRole('row').filter({ hasText: '测试新增' })
  await expect(row).toBeVisible()
  await row.getByRole('button', { name: /删\s*除/ }).click()
  await page.getByRole('button', { name: 'OK', exact: true }).click()
  await expect(row).toHaveCount(0)
})
test('保存失败时保留弹窗与输入，不伪装成功', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: '新增用户' }).click()
  const dialog = page.getByRole('dialog')
  await dialog.getByLabel('用户名').fill('失败用户')
  await dialog.getByLabel('邮箱').fill('fail@example.com')
  await dialog.getByRole('button', { name: 'OK' }).click()
  await expect(dialog).toBeVisible()
  await expect(dialog.getByLabel('邮箱')).toHaveValue('fail@example.com')
  await expect(page.getByRole('alert')).toContainText('演示保存失败')
  await expect(page.getByRole('cell', { name: '失败用户', exact: true })).toHaveCount(0)
})
